# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H3wTVpvjQBfAX_pTLnBEUur8ITKiwTxi
"""

!pip install face_recognition

import PIL.Image
import PIL.ImageDraw
import face_recognition

# Load the jpg file in a numpy array
image = face_recognition.load_image_file('/content/drive/My Drive/Colab Notebooks/people.jpg')

# Find all facial features in all the faces in the image
face_landmarks_list = face_recognition.face_landmarks(image)

number_of_faces = len(face_landmarks_list)
print('I found {} number of face(s) in the image'.format(number_of_faces))

pil_image = PIL.Image.fromarray(image)

draw = PIL.ImageDraw.Draw(pil_image)

for face_landmarks in face_landmarks_list:
  print('\n')
  for name, list_of_points in face_landmarks.items():
    print('The {} in this face has the following points: {}'.format(name, list_of_points))

    draw.line(list_of_points, fill = 'red', width = 2)

pil_image

